apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: addon-controller
  name: controller-metrics-service
  namespace: projectsveltos
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: addon-controller
