# permissions for end users to edit clusterfeatures.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterfeature-editor-role
rules:
- apiGroups:
  - config.projectsveltos.io
  resources:
  - clusterfeatures
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.projectsveltos.io
  resources:
  - clusterfeatures/status
  verbs:
  - get
