# permissions for end users to view clusterreports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterreport-viewer-role
rules:
- apiGroups:
  - config.projectsveltos.io
  resources:
  - clusterreports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.projectsveltos.io
  resources:
  - clusterreports/status
  verbs:
  - get
