# permissions for end users to edit profiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: profile-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: addon-controller
    app.kubernetes.io/part-of: addon-controller
    app.kubernetes.io/managed-by: kustomize
  name: profile-editor-role
rules:
- apiGroups:
  - config.projectsveltos.io
  resources:
  - profiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.projectsveltos.io
  resources:
  - profiles/status
  verbs:
  - get
