---
# If used to deploy resources in the management cluster
# sveltos needs to be granted needed permission. This
# ClusterRole is for that.
# If Sveltos needs to create for instance a ServiceAccount resource
# in the management cluster, Sveltos needs "*" as verbs. Sveltos
# create/patch/delete such resources, it needs to fetch (so get/list)
# and react to changes (so watch).
# ClusterRoleBinding tying this to addon-controller ServiceAccount
# is created by default when installing Sveltos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: controller-role-extra