---
# If used to deploy resources in the management cluster
# sveltos needs to be granted needed permission. This
# ClusterRole is for that.
# If Sveltos needs to create for instance a ServiceAccount resource
# in the management cluster, Sveltos needs "*" as verbs. Sveltos
# create/patch/delete such resources, it needs to fetch (so get/list)
# and react to changes (so watch).
# ClusterRoleBinding tying this to addon-controller ServiceAccount
# is created by default when installing Sveltos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controller-role-extra
---
# When sharding is used, addon-controller needs to create
# update configMaps in projectsveltos namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: controller-role-extra
  namespace: projectsveltos
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - create
  - update