# permissions for end users to edit substitutionrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: substitutionrule-editor-role
rules:
- apiGroups:
  - config.projectsveltos.io
  resources:
  - substitutionrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.projectsveltos.io
  resources:
  - substitutionrules/status
  verbs:
  - get
