# permissions for end users to view substitutionrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: substitutionrule-viewer-role
rules:
- apiGroups:
  - config.projectsveltos.io
  resources:
  - substitutionrules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.projectsveltos.io
  resources:
  - substitutionrules/status
  verbs:
  - get
