# permissions for end users to view workloadroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workloadrole-viewer-role
rules:
- apiGroups:
  - config.projectsveltos.io
  resources:
  - workloadroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.projectsveltos.io
  resources:
  - workloadroles/status
  verbs:
  - get
