# This openapi policy makes sure that each deployment has a name starting with prod

# To use this openapi policy:
# 1. save it in a file "name-convention.yaml" 
# 2. create a ConfigMap containing it: kubectl create configmap depl-name-convention --from-file=name-convention.yaml
# 3. create an AddonCompliance instance referencing it
#apiVersion: lib.projectsveltos.io/v1alpha1
#kind: AddonCompliance
#metadata:
# name: depl-name-convention
#spec:
#  clusterSelector: env=production
#  openAPIValidationRefs:
#  - namespace: default
#    name: depl-name-convention
#    kind: ConfigMap

openapi: 3.0.0
info:
  title: Name Validation Policy
  version: 1.0.0

paths:
  /apis/apps/v1/namespaces/{namespace}/deployments/{deployment}:
    put:
      parameters:
        - in: path
          name: namespace
          required: true
          schema:
            type: string
            minimum: 1
          description: The namespace of the resource
        - in: path
          name: deployment
          required: true
          schema:
            type: string
            minimum: 1
          description: The name of the resource    
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Deployment'
      responses:
        '200':
          description: OK
components:
  schemas:
    Deployment:
      type: object
      properties:
        metadata:
          type: object
          properties:
            name:
              type: string
              pattern: '^prod.*'